services:
  - type: web
    name: bookswap-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: FIREBASE_SERVICE_ACCOUNT
        sync: false
  - type: web
    name: bookswap-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist/book-swap
